### ISSUE TITLE
authentication question

### ISSUE THREAD

**Issue by workhardcc** [swqmaven/kubernetes1.4_ansible#1]
Hello,I have no idea how to run kube-dashboard when api-server authentication by token , could you pls watch this page :https://github.com/kubernetes/dashboard/issues/1116
I think you maybe resolved it already. tks!

**Comment by u2bo** [comment]
you can read the project how to config authentication!
1.you must mount the kubeconfig to the dashboard container
2.config the kubeconfig file used token authentication like:

`
apiVersion: v1
clusters:
- cluster:
  insecure-skip-tls-verify: true
  server: https://192.168.199.134:443
  name: kubernetes_tls
  contexts:
- context:
  cluster: kubernetes_tls
  user: kubeadm
  name: swq@kubernetes
  current-context: swq@kubernetes
  kind: Config
  preferences: {}
  users:
- name: kubeadm
  user:
    token: 1MVytSxl5f2X05fjnZGmvFiXkixYQUgq

`

**Comment by workhardcc** [comment]
@swqmaven  thanks for help!
I modified your config but still failed! 

```
Using HTTP port: 9090
Using apiserver-host location: https://10.93.78.11:443
Creating API server client for https://10.93.78.11:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.93.78.11:443/version: x509: failed to load system roots and no roots provided
```

All of this two kind of config I had tried it:

```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
    server: https://10.93.78.11:443
contexts:
- context:
    cluster: local
    user: vpsadmin
users:
- name: vpsadmin
  user:
    token:12343435243
```

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.93.78.11:443
  name: kubernetes_tls
contexts:
- context:
    cluster: kubernetes_tls
    user: kubeadm
  name: swq@kubernetes
current-context: swq@kubernetes
kind: Config
preferences: {}
users:
- name: kubeadm
  user:
    token:asdasdasdasdas
```

By the way, Are you Chinese? If yes, 我能加你QQ请教一下吗？2959053062
